### ISSUE TITLE
Option to disable buttons

### ISSUE THREAD

**Issue by lostdusty** [sdassow/fyne-datepicker#3]
I think there should be an option to disable these buttons:
![image](https://github.com/user-attachments/assets/eb82b492-5079-4fd3-ad52-2aa54ca5bbb5)

"Now" button is great, but I think it could be placed somewhere else.

Another idea is to trigger the callback as soon as the user selects one date.

**Comment by sdassow** [comment]
Now I think the buttons shouldn't be in there at all and I just removed them.

The "Now" button either should make it clear to affect the date as well, or it should not, then a "Today" button would be good. The positioning should probably change too, agreed. Have to think about it.

Thanks for the input!

**Comment by lostdusty** [comment]
Thanks for your work, works perfectly for me!
